GENERATE_ANIMATION = False
GENERATE_DEPTH_CURVE = False
GENERATE_DEPTH_MAP = True
GENERATE_DOF_CURVES = False
Y_ROTATE_EXP = False
INTERPOLATE_DOF = False

FRAME_RELATIVE_TRANSFORM_FILE = 'interpolate/C_G_1st.txt'